/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_regis_jprobe_jni_OSSystemInfo */

#ifndef _Included_edu_regis_jprobe_jni_OSSystemInfo
#define _Included_edu_regis_jprobe_jni_OSSystemInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_OK
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_OK 0L
#undef edu_regis_jprobe_jni_OSSystemInfo_INVALID_PARMS
#define edu_regis_jprobe_jni_OSSystemInfo_INVALID_PARMS -1L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_FAILED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_FAILED -2L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_NOT_SUPPORTED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_CALL_NOT_SUPPORTED -3L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_LIBRARY_LOAD_FAILED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_LIBRARY_LOAD_FAILED -4L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_LIBRARY_LOOKUP_FAILED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_LIBRARY_LOOKUP_FAILED -5L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_SELF_ELEVATE_FAILED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_SELF_ELEVATE_FAILED -6L
#undef edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_SELF_ELEVATE_CANCELLED
#define edu_regis_jprobe_jni_OSSystemInfo_SYSTEM_SELF_ELEVATE_CANCELLED -7L
/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getCPUAffinity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getCPUAffinity
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    setCPUAffinity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_setCPUAffinity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    setCPUAffinityToSystem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_setCPUAffinityToSystem
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getProcessHandleCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getProcessHandleCount
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getNumberOfCPUs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getNumberOfCPUs
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getIOCounters
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getIOCounters
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getProcessMemoryInfo
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getProcessMemoryInfo
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getProcessTimes
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getProcessTimes
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    emptyWorkingSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_emptyWorkingSet
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    sendCTLBreak
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_sendCTLBreak
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    sendCTLC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_sendCTLC
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getCurrentCPUId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getCurrentCPUId
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getNativeLibList
 * Signature: (Ledu/regis/jprobe/jni/OSNativeLibs;J)I
 */
JNIEXPORT jint JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getNativeLibList
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    setNativeDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_setNativeDebug
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getCurrentProcessID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getCurrentProcessID
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getCurrentThreadID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getCurrentThreadID
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    isProcessActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_isProcessActive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    isAdmin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_isAdmin
  (JNIEnv *, jclass);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    killProcess
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_killProcess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    getProcessInfo
 * Signature: (Ledu/regis/jprobe/jni/ProcessString;Z)J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_getProcessInfo
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     edu_regis_jprobe_jni_OSSystemInfo
 * Method:    selfElevate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_regis_jprobe_jni_OSSystemInfo_selfElevate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
